'''
OGNI COSTANTE E' COSI' FATTA: 
    - valore dell'angolo
    - direzione di sterzatura quando si ha un ostacolo davanti
'''

DA_INIZIO_AD_OGGETTI = (100, 0)
DA_OGGETTI_AD_AREA_ROSSA = (217, 1)
DA_AREA_ROSSA_AD_OGGETTI = (62, 0) 
DA_OGGETTI_AD_AREA_BLU = (353 , 0)
DA_AREA_BLU_AD_OGGETTI = (140, 1)
DA_OGGETTI_AD_AREA_GIALLA = (228, 1)
DA_AREA_GIALLA_AD_OGGETTI = (84, 0)

# DA_OGGETTI_AD_AREA_BLU = 340
# DA_AREA_BLU_AD_OGGETTI = 160
# DA_OGGETTI_AD_AREA_GIALLA = 0
# DA_AREA_GIALLA_AD_OGGETTI = 0

